moedas = {
    "AED": ["د.إ", "UAE Dirham"],
    "AFN": ["؋", "Afghan Afghani"],
    "ALL": ["L", "Albanian Lek"],
    "AMD": ["֏", "Armenian Dram"],
    "ANG": ["ƒ", "Netherlands Antillian Guilder"],
    "AOA": ["Kz", "Angolan Kwanza"],
    "ARS": ["$", "Argentine Peso"],
    "AUD": ["$", "Australian Dollar"],
    "AWG": ["ƒ", "Aruban Florin"],
    "AZN": ["₼", "Azerbaijani Manat"],
    "BAM": ["KM", "Bosnia and Herzegovina Convertible Mark"],
    "BBD": ["$", "Barbados Dollar"],
    "BDT": ["৳", "Bangladeshi Taka"],
    "BGN": ["лв", "Bulgarian Lev"],
    "BHD": ["ب.د", "Bahraini Dinar"],
    "BIF": ["FBu", "Burundian Franc"],
    "BMD": ["$", "Bermudian Dollar"],
    "BND": ["$", "Brunei Dollar"],
    "BOB": ["Bs.", "Bolivian Boliviano"],
    "BRL": ["R$", "Brazilian Real"],
    "BSD": ["$", "Bahamian Dollar"],
    "BTN": ["Nu.", "Bhutanese Ngultrum"],
    "BWP": ["P", "Botswana Pula"],
    "BYN": ["Br", "Belarusian Ruble"],
    "BZD": ["BZ$", "Belize Dollar"],
    "CAD": ["$", "Canadian Dollar"],
    "CDF": ["FC", "Congolese Franc"],
    "CHF": ["CHF", "Swiss Franc"],
    "CLP": ["$", "Chilean Peso"],
    "CNY": ["¥", "Chinese Renminbi"],
    "COP": ["$", "Colombian Peso"],
    "CRC": ["₡", "Costa Rican Colon"],
    "CUP": ["$", "Cuban Peso"],
    "CVE": ["$", "Cape Verdean Escudo"],
    "CZK": ["Kč", "Czech Koruna"],
    "DJF": ["Fdj", "Djiboutian Franc"],
    "DKK": ["kr", "Danish Krone"],
    "DOP": ["RD$", "Dominican Peso"],
    "DZD": ["دج", "Algerian Dinar"],
    "EGP": ["£", "Egyptian Pound"],
    "ERN": ["Nkf", "Eritrean Nakfa"],
    "ETB": ["Br", "Ethiopian Birr"],
    "EUR": ["€", "Euro"],
    "FJD": ["$", "Fiji Dollar"],
    "FKP": ["£", "Falkland Islands Pound"],
    "FOK": ["kr", "Faroese Króna"],
    "GBP": ["£", "Pound Sterling"],
    "GEL": ["₾", "Georgian Lari"],
    "GGP": ["£", "Guernsey Pound"],
    "GHS": ["₵", "Ghanaian Cedi"],
    "GIP": ["£", "Gibraltar Pound"],
    "GMD": ["D", "Gambian Dalasi"],
    "GNF": ["FG", "Guinean Franc"],
    "GTQ": ["Q", "Guatemalan Quetzal"],
    "GYD": ["$", "Guyanese Dollar"],
    "HKD": ["$", "Hong Kong Dollar"],
    "HNL": ["L", "Honduran Lempira"],
    "HRK": ["kn", "Croatian Kuna"],
    "HTG": ["G", "Haitian Gourde"],
    "HUF": ["Ft", "Hungarian Forint"],
    "IDR": ["Rp", "Indonesian Rupiah"],
    "ILS": ["₪", "Israeli New Shekel"],
    "IMP": ["£", "Manx Pound"],
    "INR": ["₹", "Indian Rupee"],
    "IQD": ["ع.د", "Iraqi Dinar"],
    "IRR": ["﷼", "Iranian Rial"],
    "ISK": ["kr", "Icelandic Króna"],
    "JEP": ["£", "Jersey Pound"],
    "JMD": ["$", "Jamaican Dollar"],
    "JOD": ["د.ا", "Jordanian Dinar"],
    "JPY": ["¥", "Japanese Yen"],
    "KES": ["KSh", "Kenyan Shilling"],
    "KGS": ["с", "Kyrgyzstani Som"],
    "KHR": ["៛", "Cambodian Riel"],
    "KID": ["$", "Kiribati Dollar"],
    "KMF": ["CF", "Comorian Franc"],
    "KRW": ["₩", "South Korean Won"],
    "KWD": ["د.ك", "Kuwaiti Dinar"],
    "KYD": ["$", "Cayman Islands Dollar"],
    "KZT": ["₸", "Kazakhstani Tenge"],
    "LAK": ["₭", "Lao Kip"],
    "LBP": ["ل.ل", "Lebanese Pound"],
    "LKR": ["Rs", "Sri Lanka Rupee"],
    "LRD": ["$", "Liberian Dollar"],
    "LSL": ["L", "Lesotho Loti"],
    "LYD": ["ل.د", "Libyan Dinar"],
    "MAD": ["د.م.", "Moroccan Dirham"],
    "MDL": ["L", "Moldovan Leu"],
    "MGA": ["Ar", "Malagasy Ariary"],
    "MKD": ["ден", "Macedonian Denar"],
    "MMK": ["K", "Burmese Kyat"],
    "MNT": ["₮", "Mongolian Tögrög"],
    "MOP": ["P", "Macanese Pataca"],
    "MRU": ["UM", "Mauritanian Ouguiya"],
    "MUR": ["₨", "Mauritian Rupee"],
    "MVR": ["ރ.", "Maldivian Rufiyaa"],
    "MWK": ["MK", "Malawian Kwacha"],
    "MXN": ["$", "Mexican Peso"],
    "MYR": ["RM", "Malaysian Ringgit"],
    "MZN": ["MT", "Mozambican Metical"],
    "NAD": ["$", "Namibian Dollar"],
    "NGN": ["₦", "Nigerian Naira"],
    "NIO": ["C$", "Nicaraguan Córdoba"],
    "NOK": ["kr", "Norwegian Krone"],
    "NPR": ["₨", "Nepalese Rupee"],
    "NZD": ["$", "New Zealand Dollar"],
    "OMR": ["ر.ع.", "Omani Rial"],
    "PAB": ["B/.", "Panamanian Balboa"],
    "PEN": ["S/", "Peruvian Sol"],
    "PGK": ["K", "Papua New Guinean Kina"],
    "PHP": ["₱", "Philippine Peso"],
    "PKR": ["₨", "Pakistani Rupee"],
    "PLN": ["zł", "Polish Złoty"],
    "PYG": ["₲", "Paraguayan Guaraní"],
    "QAR": ["ر.ق", "Qatari Riyal"],
    "RON": ["L", "Romanian Leu"],
    "RSD": ["дин.", "Serbian Dinar"],
    "RUB": ["₽", "Russian Ruble"],
    "RWF": ["RF", "Rwandan Franc"],
    "SAR": ["ر.س", "Saudi Riyal"],
    "SBD": ["$", "Solomon Islands Dollar"],
    "SCR": ["₨", "Seychellois Rupee"],
    "SDG": ["ج.س.", "Sudanese Pound"],
    "SEK": ["kr", "Swedish Krona"],
    "SGD": ["$", "Singapore Dollar"],
    "SHP": ["£", "Saint Helena Pound"],
    "SLE": ["Le", "Sierra Leonean Leone"],
    "SLL": ["Le", "Sierra Leonean Leone"],
    "SOS": ["Sh", "Somali Shilling"],
    "SRD": ["$", "Surinamese Dollar"],
    "SSP": ["£", "South Sudanese Pound"],
    "STN": ["Db", "São Tomé and Príncipe Dobra"],
    "SYP": ["£", "Syrian Pound"],
    "SZL": ["L", "Eswatini Lilangeni"],
    "THB": ["฿", "Thai Baht"],
    "TJS": ["SM", "Tajikistani Somoni"],
    "TMT": ["T", "Turkmenistan Manat"],
    "TND": ["د.ت", "Tunisian Dinar"],
    "TOP": ["T$", "Tongan Paʻanga"],
    "TRY": ["₺", "Turkish Lira"],
    "TTD": ["$", "Trinidad and Tobago Dollar"],
    "TVD": ["$", "Tuvaluan Dollar"],
    "TWD": ["NT$", "New Taiwan Dollar"],
    "TZS": ["Sh", "Tanzanian Shilling"],
    "UAH": ["₴", "Ukrainian Hryvnia"],
    "UGX": ["USh", "Ugandan Shilling"],
    "USD": ["$", "United States Dollar"],
    "UYU": ["$", "Uruguayan Peso"],
    "UZS": ["сўм", "Uzbekistani So'm"],
    "VES": ["Bs.S", "Venezuelan Bolívar Soberano"],
    "VND": ["₫", "Vietnamese Đồng"],
    "VUV": ["VT", "Vanuatu Vatu"],
    "WST": ["T", "Samoan Tālā"],
    "XAF": ["FCFA", "Central African CFA Franc"],
    "XCD": ["$", "East Caribbean Dollar"],
    "XDR": ["SDR", "Special Drawing Rights"],
    "XOF": ["CFA", "West African CFA franc"],
    "XPF": ["₣", "CFP Franc"],
    "YER": ["﷼", "Yemeni Rial"],
    "ZAR": ["R", "South African Rand"],
    "ZMW": ["ZK", "Zambian Kwacha"],
    "ZWL": ["$", "Zimbabwean Dollar"]
}
